t3kit/t3kit

- .gitmodules
> [!!!][UPDATE] Change remote on News

- typo3conf/realurl_conf.php
https://github.com/t3kit/t3kit_extension_tools/issues/10
> [!!!][FIX] fixed bug connected with old realurl hook

- .gitmodules
Hi @jozefspisiak
Please review my changing.
Thanks,
Chanpiseth
> [FEATURE] Add url_forwarding ext for editor add redirects

- .gitignore
- typo3conf/LocalConfiguration.php
- typo3conf/PackageStates.php
- typo3conf/realurl_conf.php
https://github.com/t3kit/t3kit/issues/92
https://github.com/t3kit/t3kit_extension_tools/pull/15
> [BUGFIX] not possible to change fixed post var configuration of realurl

- README.md
A small change to avoid error in non-existence of d alias
> [DOC] Reverse alias d to docker for public usage

- composer.json
Installation:
* Run composer update/install for the new package
> [!!!][TASK] Replace usage of fork with real version of typo3-themes

- docker-compose.yml
- typo3conf/AdditionalConfiguration.php
> [TASK] add mailhog/mailhog to docker and set TYPO3 to use it in..

- composer.json
- docker-compose.yml
- typo3conf/AdditionalConfiguration.php
> Update pxa cookie bar

- web/typo3conf/LocalConfiguration.php
- web/typo3conf/PackageStates.php
- web/typo3conf/realurl_conf.php
see: https://github.com/t3kit/theme_t3kit/pull/209
> [!!!][TASK] replace extension seo_basics with cs_seo

- composer.json
- web/typo3conf/LocalConfiguration.php
- web/typo3conf/PackageStates.php
need to update database (compare database in install tool)
> [!!!][FEATURE] add dashboard extension

- composer.json
- composer.lock
This commit adds the extension georgringer/gdpr which makes TYPO3
GDPR compatible. Read more here:
https://github.com/georgringer/gdpr
> [TASK] Add GDPR compability for TYPO3

- composer.json
Version 1.3.0 of this package supports TYPO3v8.
> [TASK] Allow minor updates of typo3-ter/url-forwarding

- composer.json
- composer.lock
- config/sites/t3kit/config.yaml
- web/typo3conf/PackageStates.php
> [FEATURE] TYPO3 v9 site configuration with no realurl

- web/typo3conf/PackageStates.php
see https://github.com/t3kit/theme_t3kit/pull/494
> [TASK] theme_t3kit should go after news in PackageStates.php

- Configuration/TCA/Overrides/120_tt_content_bigIconTextButton.php
- Configuration/TCA/Overrides/91_tt_content_table.php
- Configuration/TSconfig/Page/Mod/Wizards/ContentElements/Static/1.tsconfig
- Configuration/TypoScript/ContentElements/Static/Table.typoscript
- Resources/Private/Language/locallang_BE_CE.xlf
- Resources/Private/Layouts/ContentElements/Default.html
- Resources/Private/Partials/ContentElements/Media/Type/Image.html
- Resources/Private/Templates/ContentElements/Static/BigIconTextButton.html
- Resources/Private/Templates/ContentElements/Static/Table.html
- Resources/Private/Templates/ContentElements/Static/Uploads.html
- ext_tables.sql
> Check c es

- Configuration/TCA/Overrides/50_sys_template.php
- Configuration/TypoScript/Extensions/indexed_search/setup.typoscript
- Configuration/TypoScript/Lib/ContentElement.typoscript
- Configuration/TypoScript/Lib/ContentObject.typoscript
- Resources/Private/Extensions/indexed_search/Templates/HeaderMiddleSearch.html
- Resources/Private/Extensions/indexed_search/Templates/HeaderTopSearch.html
- Resources/Private/Extensions/indexed_search/Templates/MainNavigationSearch.html
- Resources/Private/Templates/ContentElements/Special/SiteHeader.html
> [FEATURE] Indexed search templates

- Configuration/TCA/tx_t3kit_slider_item.php
- Resources/Private/Language/ContentElements/Dynamic/locallang_slider.xlf
- Resources/Private/Templates/ContentElements/Dynamic/Slider.html
- ext_tables.sql
- theme/src/scss/content-elements/slider.scss
Adds option for overlay on each slide in the slider element
> [FEATURE] add option for overlay on each slide

- .github/workflows/code-guidelines.yml
- .github/workflows/git-commit.yml
> [TEST] update github actions, predefine php version, add composer cache

- .github/workflows/code-guidelines.yml
- .husky/pre-commit
- package-lock.json
- package.json
> [TEST] update git hooks, ignore husky install on github actions'

- Configuration/TypoScript/ContentElement/Groups/Special/SiteFooter.typoscript
- Resources/Private/Templates/ContentElements/Special/SiteFooter.html
> [TASK] add possibility to link target_blank for footer links

- theme/src/css/main/content-elements/textpic.css
Aligning/containing the caption under the image to not go beyond the image edge in CE textpic
> [BUGFIX] align image description under images in CE textpic

- Classes/View/IconView.php
Prevent "Undefined array key 0" error in PHP 8
> [BUGFIX] Prevent "Undefined array key 0" error in PHP 8

- theme/src/css/main.css
- theme/src/css/main/content-elements/text.css
Fixes: #49
Issue Number: #49
Ticket is in another repo, but code related to this one: https://github.com/t3kit/t3kit-starter/issues/49
> [BUGFIX] Add correct styling for lists with center/right alignment

- composer.json
Add typo3/* to allow-plugins in allow-plugins config.
> [TASK] Add typo3/* to allow-plugins in allow-plugins config
